# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_pengurangan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets  import QDialog
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QLabel, QMainWindow, QVBoxLayout, QWidget, QPushButton,QFileDialog, QDialog
from PyQt5.QtGui import QPixmap, QColor, QImage, qRgb
from PyQt5.QtCore import Qt


class Ui_ao_pembagian(QDialog):
    def setupUi(self, ao_pembagian):
        ao_pembagian.setObjectName("ao_pembagian")
        ao_pembagian.resize(1236, 928)
        self.Img1 = QtWidgets.QLabel(ao_pembagian)
        self.Img1.setGeometry(QtCore.QRect(10, 90, 601, 381))
        self.Img1.setFrameShape(QtWidgets.QFrame.Box)
        self.Img1.setAlignment(QtCore.Qt.AlignCenter)
        self.Img1.setObjectName("Img1")
        self.Img2 = QtWidgets.QLabel(ao_pembagian)
        self.Img2.setGeometry(QtCore.QRect(620, 90, 601, 381))
        self.Img2.setFrameShape(QtWidgets.QFrame.Box)
        self.Img2.setAlignment(QtCore.Qt.AlignCenter)
        self.Img2.setObjectName("Img2")
        self.LOutput = QtWidgets.QLabel(ao_pembagian)
        self.LOutput.setGeometry(QtCore.QRect(320, 480, 601, 441))
        self.LOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.LOutput.setText("")
        self.LOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.LOutput.setObjectName("LOutput")
        self.btn_proses = QtWidgets.QPushButton(ao_pembagian)
        self.btn_proses.setGeometry(QtCore.QRect(500, 20, 241, 41))
        self.btn_proses.setObjectName("btn_proses")
        self.btn_proses.clicked.connect(self.prosesPembagian)
        self.btn_open = QtWidgets.QPushButton(ao_pembagian)
        self.btn_open.setGeometry(QtCore.QRect(220, 20, 241, 41))
        self.btn_open.setObjectName("btn_open")
        self.btn_open.clicked.connect(self.loadImage2)
        self.btn_save = QtWidgets.QPushButton(ao_pembagian)
        self.btn_save.setGeometry(QtCore.QRect(780, 20, 241, 41))
        self.btn_save.setObjectName("btn_save")
        self.btn_save.clicked.connect(self.saveImage)

        self.retranslateUi(ao_pembagian)
        QtCore.QMetaObject.connectSlotsByName(ao_pembagian)

    def retranslateUi(self, ao_pembagian):
        _translate = QtCore.QCoreApplication.translate
        ao_pembagian.setWindowTitle(_translate("ao_pembagian", "Arithmathic Operation-Pengurangan"))
        self.Img1.setText(_translate("ao_pembagian", "Image 1"))
        self.Img2.setText(_translate("ao_pembagian", "Image 2"))
        self.btn_proses.setText(_translate("ao_pembagian", "Proses"))
        self.btn_open.setText(_translate("ao_pembagian", "Open"))
        self.btn_save.setText(_translate("ao_pembagian", "Save"))
    
    def loadImage2(self):
        if self.Img1.pixmap() is not None:
            options = QFileDialog.Options()
            file_name, _ = QFileDialog.getOpenFileName(self, "Open Image 2", "", "Images (*.png *.jpg *.bmp *.jpeg);;All Files (*)", options=options)
            if file_name:
                pixmap = QPixmap(file_name)
                self.Img2.setPixmap(pixmap)
                self.Img2.setScaledContents(True)
                self.displayed_pixmap = pixmap
        
        else :
            options = QFileDialog.Options()
            file_name, _ = QFileDialog.getOpenFileName(self, "Open Image 1", "", "Images (*.png *.jpg *.bmp *.jpeg);;All Files (*)", options=options)
            if file_name:
                pixmap = QPixmap(file_name)
                self.Img1.setPixmap(pixmap)
                self.Img1.setScaledContents(True)
    
    def prosesPembagian(self):
        pixmap1 = self.Img1.pixmap()
        pixmap2 = self.Img2.pixmap()
        if pixmap1 and pixmap2 :
            img1 = pixmap1.toImage()
            img2 = pixmap2.toImage()

            if img1.size() != img2.size():
                self.LOutput.setText("gambar harus memiliki ukuran yg sama")

            resul_keseluruhan = QImage(img1.size(), QImage.Format_RGB32)
            for x in range(img1.width()):
                for y in range(img1.height()):
                    pixel1 = QColor(img1.pixel(x,y))
                    pixel2 = QColor(img2.pixel(x,y))
            
                    if pixel2.red() == 0 or pixel2.green() == 0 or pixel2.blue() == 0:
                        # Atur nilai hasil ke nol (atau nilai default lainnya)
                        r = 0
                        g = 0
                        b = 0
                    else:
                        # Lakukan pembagian hanya jika pixel kedua tidak nol
                        r = pixel1.red() / pixel2.red()
                        g = pixel1.green() / pixel2.green()
                        b = pixel1.blue() / pixel2.blue()
                    

                    # Batasi nilai antara 0 dan 255
                    r = max(min(r, 255), 0)
                    g = max(min(g, 255), 0)
                    b = max(min(b, 255), 0)
                    resul_keseluruhan.setPixel(x,y , qRgb(int(r), int(g),int(b) ))

            jumlah_pixmap = QPixmap.fromImage(resul_keseluruhan)
            self.LOutput.setPixmap(jumlah_pixmap)
            self.LOutput.setScaledContents(True)
            self.displayed_pixmap = jumlah_pixmap
    
    def saveImage(self):
        pixmap = self.LOutput.pixmap()
        if pixmap:
            saveFile = QtWidgets.QFileDialog()
            saveFile.setAcceptMode(QtWidgets.QFileDialog.AcceptSave)
            saveFile.setNameFilter("JPG File(*.jpg);; PNG FIles(*.png)")

            if saveFile.exec_() == QtWidgets.QDialog.Accepted:
                save_path = saveFile.selectedFiles()[0]
                self.displayed_pixmap.save(save_path)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ao_pengurangan = QtWidgets.QWidget()
    ui = Ui_ao_pembagian()
    ui.setupUi(ao_pengurangan)
    ao_pengurangan.show()
    sys.exit(app.exec_())
